export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const SAVE_FORM_DATA_REQUEST = 'SAVE_FORM_DATA_REQUEST';
export const SAVE_FORM_DATA_FAILURE = 'SAVE_FORM_DATA_FAILURE';